[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  [functions."nuvizz-pull-today-stops"]
    timeout = 26
  [functions."nuvizz-manual-scan"]
    timeout = 26
  [functions."motive-driver-positions"]
    timeout = 10

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
